# Generated by Django 3.0.4 on 2020-03-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('lab_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lab.Lab')),
                ('role_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Lab.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('air_quality', models.FloatField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('request_to', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('Notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.User')),
            ],
        ),
    ]
