# Generated by Django 3.0.4 on 2020-03-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lab_id',
        ),
    ]
